// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvBe_IuqRcsekPg6UqAz-qevrUglHIFG4',
    appId: '1:1035671940710:web:b569fe47c138d0b2bb47a7',
    messagingSenderId: '1035671940710',
    projectId: 'hackathonapp-f439f',
    authDomain: 'hackathonapp-f439f.firebaseapp.com',
    storageBucket: 'hackathonapp-f439f.appspot.com',
    measurementId: 'G-Z2ECG409G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dRCJ9i8MbVFuah4DRX3UiztneLHKBGk',
    appId: '1:1035671940710:android:0381f36556ea12a2bb47a7',
    messagingSenderId: '1035671940710',
    projectId: 'hackathonapp-f439f',
    storageBucket: 'hackathonapp-f439f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuv3bWKct6APbxqTBLt1JEYRuhyzB7sdQ',
    appId: '1:1035671940710:ios:a328c82cca0824a6bb47a7',
    messagingSenderId: '1035671940710',
    projectId: 'hackathonapp-f439f',
    storageBucket: 'hackathonapp-f439f.appspot.com',
    iosClientId: '1035671940710-ethlcvm7c28639040a6jbktaue1pvv1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
